# Generated by Django 3.0 on 2021-06-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defib_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Defib_Id', models.IntegerField()),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('Pressure', models.FloatField()),
                ('Battery', models.FloatField()),
            ],
            options={
                'ordering': ['Data_DateTime'],
            },
        ),
    ]
