# Generated by Django 3.0 on 2021-06-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_defib_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defib_data',
            name='Data_DateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
