# Generated by Django 3.0 on 2021-06-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210628_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defib_data',
            name='Battery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defib_data',
            name='Defib_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defib_data',
            name='Humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defib_data',
            name='Pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defib_data',
            name='Temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
