# Generated by Django 3.0 on 2021-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210629_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='picarro_data',
            name='Data_DryA',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picarro_data',
            name='Data_GrassA',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picarro_data',
            name='Data_HumA',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picarro_data',
            name='Data_MaxGust',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picarro_data',
            name='Data_MaxGustDir',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picarro_data',
            name='Data_Pressure',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picarro_data',
            name='Data_WindDir',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picarro_data',
            name='Data_WindSpeed',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
