# Generated by Django 3.0 on 2021-12-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_nox_data_sox_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sox_data',
            name='Data_Sox_Pressure',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
