# Generated by Django 3.0 on 2021-12-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_sox_data_data_sox_pressure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Name', models.CharField(max_length=50)),
                ('Location_Description', models.CharField(max_length=200)),
                ('Location_Lat', models.CharField(max_length=20)),
                ('Location_Lng', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['Location_Name'],
            },
        ),
        migrations.CreateModel(
            name='Node_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Name', models.CharField(max_length=50)),
                ('Type_Description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['Type_Name'],
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Node_Name', models.CharField(max_length=50)),
                ('Node_Description', models.CharField(max_length=200)),
                ('Node_Ip', models.CharField(max_length=20)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Node_Location')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Node_Type')),
            ],
            options={
                'ordering': ['Node_Name'],
            },
        ),
    ]
