# Generated by Django 3.2.11 on 2022-01-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_node_location_node_type_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(max_length=50)),
                ('Client_Description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['Client_Name'],
            },
        ),
        migrations.AddField(
            model_name='node_location',
            name='Location_Site',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node_type',
            name='Type_Make',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node_type',
            name='Type_Model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='Asset_Ip',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='Asset_Status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='Data_Status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='Node_ID',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='Node_Status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='Server_Status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='Client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.clients'),
            preserve_default=False,
        ),
    ]
