# Generated by Django 3.2.11 on 2022-01-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_node_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_type',
            name='Type_Args',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='node_type',
            name='Type_Kwargs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
