# Generated by Django 3.2.11 on 2022-01-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20220116_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.node_category'),
            preserve_default=False,
        ),
    ]
