# Generated by Django 3.2.11 on 2022-01-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_nodes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node_location',
            name='Location_Site',
        ),
        migrations.AddField(
            model_name='nodes',
            name='Node_Lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='Node_Lng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='Node_X',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='Node_Y',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='Node_Z',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Node_Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Name', models.CharField(max_length=50)),
                ('Site_Description', models.CharField(max_length=200)),
                ('Location_Lat', models.CharField(max_length=20)),
                ('Location_Lng', models.CharField(max_length=20)),
                ('Location_Site', models.CharField(max_length=50)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.node_location')),
            ],
            options={
                'ordering': ['Site_Name'],
            },
        ),
    ]
