# Generated by Django 3.2.11 on 2022-01-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20220116_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node_site',
            name='Location',
        ),
        migrations.AddField(
            model_name='node_location',
            name='Site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.node_site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node_location',
            name='Location_Lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='node_location',
            name='Location_Lng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='node_site',
            name='Location_Lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='node_site',
            name='Location_Lng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='node_site',
            name='Location_Site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='node_type',
            name='Type_Make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='node_type',
            name='Type_Model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='Asset_Ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='Node_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='Node_Ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
