# Generated by Django 3.2.11 on 2022-01-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20220118_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node_location',
            name='Site',
        ),
        migrations.DeleteModel(
            name='Node_Site',
        ),
    ]
