# Generated by Django 3.2.11 on 2022-01-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20220118_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='picarro_data',
            name='Node_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.nodes'),
            preserve_default=False,
        ),
    ]
