# Generated by Django 3.2.11 on 2022-01-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_nodes_node_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='Node_Device_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
