# Generated by Django 3.2.11 on 2022-01-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20220121_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='Status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
