# Generated by Django 3.2.11 on 2022-01-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_nodes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='Data_Status',
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='Data_Status_Description',
        ),
    ]
