# Generated by Django 3.2.11 on 2022-01-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20220121_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='sox_data',
            name='Node_ID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='data.nodes'),
            preserve_default=False,
        ),
    ]
