# Generated by Django 3.2.11 on 2022-01-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_sox_data_node_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autosonde_Soundings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_Day', models.DateTimeField(verbose_name='date published')),
                ('Data_Type', models.CharField(max_length=5)),
                ('Data_Stage_1', models.DateTimeField(verbose_name='date published')),
                ('Data_Stage_2', models.DateTimeField(verbose_name='date published')),
                ('Data_Stage_3', models.DateTimeField(verbose_name='date published')),
                ('Data_Stage_4', models.DateTimeField(verbose_name='date published')),
                ('Data_Stage_5', models.DateTimeField(verbose_name='date published')),
                ('Data_Stage_6', models.DateTimeField(verbose_name='date published')),
                ('Data_Stage_7', models.DateTimeField(verbose_name='date published')),
                ('Node_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.nodes')),
            ],
            options={
                'ordering': ['Data_Day'],
            },
        ),
        migrations.CreateModel(
            name='Autosonde_Sounding_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Data_EVSS', models.FloatField()),
                ('Data_Pressure', models.FloatField()),
                ('Data_Geopotential_Height', models.FloatField()),
                ('Data_Lat', models.FloatField()),
                ('Data_Lng', models.FloatField()),
                ('Data_Air_Temperature', models.FloatField()),
                ('Data_Dewpoint_Temperature', models.FloatField()),
                ('Data_Direction', models.FloatField()),
                ('Data_Speed', models.FloatField()),
                ('Sounding_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.autosonde_soundings')),
            ],
            options={
                'ordering': ['Data_DateTime'],
            },
        ),
        migrations.CreateModel(
            name='Autosonde_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Log_Type', models.IntegerField()),
                ('Log_Details', models.CharField(max_length=200)),
                ('Sounding_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.autosonde_soundings')),
            ],
            options={
                'ordering': ['Log_DateTime'],
            },
        ),
    ]
