# Generated by Django 3.2.11 on 2022-01-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_autosonde_logs_autosonde_sounding_data_autosonde_soundings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autosonde_Ground_Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Met_Gust_Max', models.FloatField()),
                ('Met_Gust_Direction', models.FloatField()),
                ('Met_Wind_Direction', models.FloatField()),
                ('Met_Wind_Speed', models.FloatField()),
                ('Met_Pressure', models.FloatField()),
                ('Met_Temperature_Dry', models.FloatField()),
                ('Met_Temperature_Grass', models.FloatField()),
                ('Met_Humidity', models.FloatField()),
                ('Station_Supply_Voltage', models.FloatField()),
                ('Station_Supply_L1', models.FloatField()),
                ('Station_Supply_L2', models.FloatField()),
                ('Station_Supply_L3', models.FloatField()),
                ('Station_UPS_Battery_Level', models.FloatField()),
                ('Station_UPS_Battery_Voltage', models.FloatField()),
                ('Station_UPS_Est_Run_Time', models.FloatField()),
                ('Station_UPS_Frequency', models.FloatField()),
                ('Station_UPS_Load', models.FloatField()),
                ('Station_UPS_Status', models.IntegerField()),
                ('Station_UPS_Output_Voltage', models.FloatField()),
                ('Station_UPS_Temperature', models.FloatField()),
                ('Sounding_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.autosonde_soundings')),
            ],
            options={
                'ordering': ['Data_DateTime'],
            },
        ),
    ]
