# Generated by Django 3.2.11 on 2022-01-29 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20220128_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autosonde_ground_station',
            name='Sounding_ID',
        ),
        migrations.RemoveField(
            model_name='autosonde_logs',
            name='Sounding_ID',
        ),
        migrations.AddField(
            model_name='autosonde_ground_station',
            name='Node_ID',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='data.nodes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autosonde_logs',
            name='Node_ID',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='data.nodes'),
            preserve_default=False,
        ),
    ]
