# Generated by Django 3.2.11 on 2022-02-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20220129_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='nox_data',
            name='Node_ID',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='data.nodes'),
            preserve_default=False,
        ),
    ]
