# Generated by Django 3.2.11 on 2022-02-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_nox_data_node_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nox_data',
            name='Data_Sample_Press',
        ),
    ]
