# Generated by Django 3.2.11 on 2022-02-09 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_remove_nox_data_data_sample_press'),
    ]

    operations = [
        migrations.AddField(
            model_name='tucson_data',
            name='Node_ID',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='data.nodes'),
            preserve_default=False,
        ),
    ]
