# Generated by Django 3.2.11 on 2022-02-09 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_tucson_data_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aethalometer_data',
            name='Data_DryA',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aethalometer_data',
            name='Data_GrassA',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aethalometer_data',
            name='Data_HumA',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aethalometer_data',
            name='Data_MaxGust',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aethalometer_data',
            name='Data_MaxGustDir',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aethalometer_data',
            name='Data_Pressure',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aethalometer_data',
            name='Data_WindDir',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aethalometer_data',
            name='Data_WindSpeed',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aethalometer_data',
            name='Node_ID',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='data.nodes'),
            preserve_default=False,
        ),
    ]
