# Generated by Django 3.2.11 on 2022-02-10 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20220209_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Supply_Voltage', models.FloatField()),
                ('Supply_L1', models.FloatField()),
                ('Supply_L2', models.FloatField()),
                ('Supply_L3', models.FloatField()),
                ('UPS_Battery_Level', models.FloatField()),
                ('UPS_Battery_Voltage', models.FloatField()),
                ('UPS_Est_Run_Time', models.FloatField()),
                ('UPS_Frequency', models.FloatField()),
                ('UPS_Load', models.FloatField()),
                ('UPS_Status', models.IntegerField()),
                ('UPS_Output_Voltage', models.FloatField()),
                ('UPS_Temperature', models.FloatField()),
                ('Node_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.nodes')),
            ],
            options={
                'ordering': ['Data_DateTime'],
            },
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Generator_Voltage', models.FloatField()),
                ('Generator_L1', models.FloatField()),
                ('Generator_L2', models.FloatField()),
                ('Generator_L3', models.FloatField()),
                ('Generator_Battery_Level', models.FloatField()),
                ('Generator_Battery_Voltage', models.FloatField()),
                ('Generator_Frequency', models.FloatField()),
                ('Generator_Load', models.FloatField()),
                ('Generator_Status', models.IntegerField()),
                ('Generator_Output_Voltage', models.FloatField()),
                ('Generator_Oil_Temperature', models.FloatField()),
                ('Generator_Coolent_Temperature', models.FloatField()),
                ('Generator_Oil_Pressure', models.FloatField()),
                ('Generator_Fuel_Level', models.FloatField()),
                ('Generator_Running_Hours', models.FloatField()),
                ('Node_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.nodes')),
            ],
            options={
                'ordering': ['Data_DateTime'],
            },
        ),
    ]
