# Generated by Django 3.2.11 on 2022-04-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_generator_ups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMMS_Job_Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Priority_Title', models.CharField(max_length=100)),
                ('Job_Priority_Description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['Job_Priority_Title'],
            },
        ),
        migrations.CreateModel(
            name='CMMS_Job_Schedule_Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Schedule_Period', models.CharField(max_length=100)),
                ('Job_Schedule_Period_Description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['Job_Schedule_Period'],
            },
        ),
        migrations.CreateModel(
            name='CMMS_Job_Schedule_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Schedule_Type_Title', models.CharField(max_length=100)),
                ('Job_Schedule_Type_Description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['Job_Schedule_Type_Title'],
            },
        ),
        migrations.CreateModel(
            name='CMMS_Job_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Status_Title', models.CharField(max_length=100)),
                ('Job_Status_Description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['Job_Status_Title'],
            },
        ),
        migrations.CreateModel(
            name='CMMS_Job_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Type_Title', models.CharField(max_length=100)),
                ('Job_Type_Description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['Job_Type_Title'],
            },
        ),
        migrations.CreateModel(
            name='CMMS_Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Created_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Job_Title', models.CharField(max_length=100)),
                ('Job_Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Job_Start_Date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('Job_End_Date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('Job_Completed_Comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('Job_Priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cmms_job_priority')),
                ('Job_Schedule_Period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.cmms_job_schedule_period')),
                ('Job_Schedule_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.cmms_job_schedule_type')),
                ('Job_Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cmms_job_status')),
                ('Job_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cmms_job_types')),
                ('Node_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.nodes')),
            ],
            options={
                'ordering': ['Job_Created_DateTime'],
            },
        ),
        migrations.CreateModel(
            name='CMMS_Job_Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Task_Title', models.CharField(max_length=100)),
                ('Job_Task_Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Job_Task_Completed_Date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('Job_Task_Completed_Comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cmms_jobs')),
            ],
            options={
                'ordering': ['Job_Task_Title'],
            },
        ),
        migrations.CreateModel(
            name='CMMS_Job_Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Attachment_Title', models.CharField(max_length=100)),
                ('Job_Attachment_Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Job_Attachment_Filepath', models.FileField(null=True, upload_to='files/', verbose_name='')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cmms_jobs')),
            ],
            options={
                'ordering': ['Job_Attachment_Title'],
            },
        ),
    ]
