# Generated by Django 3.2.11 on 2022-04-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_cmms_job_attachments_cmms_job_priority_cmms_job_schedule_period_cmms_job_schedule_type_cmms_job_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmms_jobs',
            name='Job_Schedule_Period_Value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cmms_job_tasks',
            name='Job_Task_Completed_Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date completed'),
        ),
        migrations.AlterField(
            model_name='cmms_jobs',
            name='Job_End_Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='cmms_jobs',
            name='Job_Start_Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
