# Generated by Django 3.2.11 on 2022-04-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_auto_20220406_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmms_job_tasks',
            name='Job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks', to='data.cmms_jobs'),
        ),
    ]
