# Generated by Django 3.2.11 on 2022-04-07 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0035_alter_cmms_job_tasks_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmms_jobs',
            name='author',
            field=models.ForeignKey(db_column='user', default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
