# Generated by Django 3.2.11 on 2022-04-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_rename_author_cmms_jobs_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMMS_Job_Task_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Task_Status_Title', models.CharField(max_length=100)),
                ('Job_Task_Status_Description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['Job_Task_Status_Title'],
            },
        ),
        migrations.AddField(
            model_name='cmms_jobs',
            name='Job_Completed_Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date completed'),
        ),
        migrations.AddField(
            model_name='cmms_job_tasks',
            name='Job_Task_Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.cmms_job_task_status'),
        ),
    ]
