# Generated by Django 3.2.11 on 2022-04-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_auto_20220407_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmms_job_tasks',
            name='Job_Task_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CMMS_Job_Task_Status',
        ),
    ]
