# Generated by Django 3.2.11 on 2022-04-12 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_auto_20220407_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmms_jobs',
            name='Job_Created_DateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
