# Generated by Django 3.2.11 on 2022-04-12 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0040_alter_cmms_jobs_job_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmms_jobs',
            name='Author',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
