# Generated by Django 3.2.11 on 2022-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_alter_cmms_jobs_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='Last_Updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last updated'),
        ),
    ]
