# Generated by Django 3.2.11 on 2022-04-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_nodes_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAQC_Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field_ID', models.CharField(max_length=200)),
                ('Field_Display_Name', models.CharField(max_length=200)),
                ('Node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.nodes')),
            ],
            options={
                'ordering': ['Node'],
            },
        ),
        migrations.CreateModel(
            name='DAQC_Change_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Change_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Origional_Value', models.FloatField()),
                ('New_Value', models.FloatField()),
                ('Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.daqc_fields')),
            ],
            options={
                'ordering': ['Field'],
            },
        ),
    ]
