# Generated by Django 3.2.11 on 2022-09-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_water', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter_Readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Pulse_Count', models.IntegerField()),
                ('Pulses', models.IntegerField()),
                ('Meter_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_water.meter_list')),
            ],
            options={
                'ordering': ['Data_DateTime'],
            },
        ),
    ]
