# Generated by Django 3.2.11 on 2022-10-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_water', '0002_meter_readings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter_Readings_Ave_WDH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Updated', models.DateTimeField(verbose_name='date published')),
                ('Day_0', models.CharField(blank=True, max_length=200, null=True)),
                ('Day_1', models.CharField(blank=True, max_length=200, null=True)),
                ('Day_2', models.CharField(blank=True, max_length=200, null=True)),
                ('Day_3', models.CharField(blank=True, max_length=200, null=True)),
                ('Day_4', models.CharField(blank=True, max_length=200, null=True)),
                ('Day_5', models.CharField(blank=True, max_length=200, null=True)),
                ('Day_6', models.CharField(blank=True, max_length=200, null=True)),
                ('Meter_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_water.meter_list')),
            ],
            options={
                'ordering': ['Last_Updated'],
            },
        ),
    ]
