# Generated by Django 3.2.11 on 2022-10-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_water', '0003_meter_readings_ave_wdh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter_readings_ave_wdh',
            name='Day_0',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='meter_readings_ave_wdh',
            name='Day_1',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='meter_readings_ave_wdh',
            name='Day_2',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='meter_readings_ave_wdh',
            name='Day_3',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='meter_readings_ave_wdh',
            name='Day_4',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='meter_readings_ave_wdh',
            name='Day_5',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='meter_readings_ave_wdh',
            name='Day_6',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
