# Generated by Django 3.2.11 on 2024-03-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_organization_organization_navigation'),
        ('app_water', '0004_auto_20221006_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter_list',
            name='Organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
    ]
