# Generated by Django 3.2.11 on 2022-07-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=50)),
                ('Category_Description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['Category_Name'],
            },
        ),
        migrations.CreateModel(
            name='Node_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Data_Table', models.CharField(blank=True, max_length=50, null=True)),
                ('Start_Index', models.FloatField()),
                ('Start_Date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('Pulse_Unit_Measurement', models.CharField(blank=True, max_length=20, null=True)),
                ('Pulse_Unit_Value', models.FloatField()),
                ('AppEUI', models.CharField(blank=True, max_length=16, null=True)),
                ('DevEUI', models.CharField(blank=True, max_length=16, null=True)),
                ('AppKey', models.CharField(blank=True, max_length=32, null=True)),
                ('Lat', models.CharField(blank=True, max_length=20, null=True)),
                ('Lng', models.CharField(blank=True, max_length=20, null=True)),
                ('X', models.CharField(blank=True, max_length=20, null=True)),
                ('Y', models.CharField(blank=True, max_length=20, null=True)),
                ('Z', models.CharField(blank=True, max_length=20, null=True)),
                ('Status', models.IntegerField()),
                ('Status_Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Kwargs', models.CharField(blank=True, max_length=200, null=True)),
                ('Args', models.CharField(blank=True, max_length=200, null=True)),
                ('Last_Updated', models.DateTimeField(blank=True, null=True, verbose_name='last updated')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dalys.node_category')),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Node_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region_Name', models.CharField(max_length=50)),
                ('Region_Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Region_Lat', models.CharField(blank=True, max_length=20, null=True)),
                ('Region_Lng', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['Region_Name'],
            },
        ),
        migrations.CreateModel(
            name='Node_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Name', models.CharField(max_length=50)),
                ('Type_Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Type_Make', models.CharField(blank=True, max_length=50, null=True)),
                ('Type_Model', models.CharField(blank=True, max_length=50, null=True)),
                ('Type_Kwargs', models.CharField(blank=True, max_length=200, null=True)),
                ('Type_Args', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['Type_Name'],
            },
        ),
        migrations.CreateModel(
            name='Node_Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Pulses', models.FloatField()),
                ('Battery_Level', models.FloatField()),
                ('Battery_Voltage', models.FloatField()),
                ('Node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dalys.node_list')),
            ],
            options={
                'ordering': ['Data_DateTime'],
            },
        ),
        migrations.CreateModel(
            name='Node_Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_DateTime', models.DateTimeField(verbose_name='date published')),
                ('RealPower_L1', models.FloatField()),
                ('RealPower_L2', models.FloatField()),
                ('RealPower_L3', models.FloatField()),
                ('AppaPower_L1', models.FloatField()),
                ('AppaPower_L2', models.FloatField()),
                ('AppaPower_L3', models.FloatField()),
                ('Irms_L1', models.FloatField()),
                ('Irms_L2', models.FloatField()),
                ('Irms_L3', models.FloatField()),
                ('Vrms_L1', models.FloatField()),
                ('Vrms_L2', models.FloatField()),
                ('Vrms_L3', models.FloatField()),
                ('PowerFact_L1', models.FloatField()),
                ('PowerFact_L2', models.FloatField()),
                ('PowerFact_L3', models.FloatField()),
                ('Node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dalys.node_list')),
            ],
            options={
                'ordering': ['Data_DateTime'],
            },
        ),
        migrations.AddField(
            model_name='node_list',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dalys.node_region'),
        ),
        migrations.AddField(
            model_name='node_list',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dalys.node_type'),
        ),
    ]
