# Generated by Django 3.2.11 on 2022-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dalys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_list',
            name='UUID',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
