# Generated by Django 3.2.11 on 2022-07-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dalys', '0002_node_list_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_list',
            name='Pulse_Unit_Value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node_list',
            name='Start_Index',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
