# Generated by Django 3.2.11 on 2023-03-19 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dalys', '0003_auto_20220707_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node_Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Battery_MV', models.FloatField()),
                ('Battery_Percent', models.FloatField()),
                ('Temperature', models.FloatField()),
                ('Node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dalys.node_list')),
            ],
            options={
                'ordering': ['Data_DateTime'],
            },
        ),
    ]
