# Generated by Django 3.2.11 on 2023-04-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dalys', '0004_node_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports_Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level_Name', models.CharField(max_length=50)),
                ('Level_ID', models.IntegerField(blank=True, null=True)),
                ('Level_LevelImagePath', models.CharField(blank=True, max_length=50, null=True)),
                ('Level_xOffset', models.FloatField(blank=True, null=True)),
                ('Level_xConst', models.FloatField(blank=True, null=True)),
                ('Level_zOffset', models.FloatField(blank=True, null=True)),
                ('Level_zConst', models.FloatField(blank=True, null=True)),
                ('Level_meXOffset', models.FloatField(blank=True, null=True)),
                ('Level_meXConst', models.FloatField(blank=True, null=True)),
                ('Level_meZOffset', models.FloatField(blank=True, null=True)),
                ('Level_meZConst', models.FloatField(blank=True, null=True)),
                ('Level_Rotate', models.IntegerField(blank=True, null=True)),
                ('Level_FlipMe', models.IntegerField(blank=True, null=True)),
                ('Level_Kwargs', models.CharField(blank=True, max_length=200, null=True)),
                ('Level_Args', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['Level_Name'],
            },
        ),
        migrations.CreateModel(
            name='Reports_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Name', models.CharField(max_length=50)),
                ('Model_MportID', models.CharField(blank=True, max_length=200, null=True)),
                ('Model_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Model_Kwargs', models.CharField(blank=True, max_length=200, null=True)),
                ('Model_Args', models.CharField(blank=True, max_length=200, null=True)),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dalys.reports_levels')),
            ],
            options={
                'ordering': ['Model_Name'],
            },
        ),
        migrations.CreateModel(
            name='Reports_Scans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scan_Name', models.CharField(max_length=50)),
                ('Scan_PID', models.CharField(blank=True, max_length=50, null=True)),
                ('Scan_Value', models.CharField(blank=True, max_length=50, null=True)),
                ('Scan_Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Scan_Xpos', models.CharField(blank=True, max_length=50, null=True)),
                ('Scan_Zpos', models.CharField(blank=True, max_length=50, null=True)),
                ('Scan_Show', models.IntegerField(blank=True, null=True)),
                ('Scan_Color', models.CharField(blank=True, max_length=50, null=True)),
                ('Scan_Number', models.IntegerField(blank=True, null=True)),
                ('Scan_Kwargs', models.CharField(blank=True, max_length=200, null=True)),
                ('Scan_Args', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['Scan_Name'],
            },
        ),
        migrations.CreateModel(
            name='Reports_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=50)),
                ('Project_Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Project_Status', models.IntegerField()),
                ('Project_Kwargs', models.CharField(blank=True, max_length=200, null=True)),
                ('Project_Args', models.CharField(blank=True, max_length=200, null=True)),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dalys.reports_models')),
            ],
            options={
                'ordering': ['Project_Name'],
            },
        ),
        migrations.AddField(
            model_name='reports_levels',
            name='Scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dalys.reports_scans'),
        ),
    ]
