# Generated by Django 3.2.11 on 2023-04-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dalys', '0005_auto_20230404_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_project',
            name='Model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_dalys.reports_models'),
        ),
    ]
