# Generated by Django 3.2.11 on 2022-04-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_Name', models.CharField(max_length=50)),
                ('Organization_Description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['Organization_Name'],
            },
        ),
    ]
