# Generated by Django 3.2.11 on 2022-04-04 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
            preserve_default=False,
        ),
    ]
