# Generated by Django 3.2.11 on 2022-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='Organization_Navigation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
