# Generated by Django 3.2.11 on 2022-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kraken_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_DateTime', models.DateTimeField(verbose_name='date published')),
                ('Market', models.CharField(max_length=20)),
                ('Open', models.FloatField()),
                ('Close', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Volume', models.FloatField()),
            ],
            options={
                'ordering': ['Data_DateTime'],
            },
        ),
    ]
